config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resources :manufacturers
  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer,
    presence: true

  validates :color,
    presence: true,
    format: { with: /\A[a-zA-Z]+\z/ }

  validates :year,
    presence: true

  validates :mileage,
    presence: true,
    numericality: { only_integer: true,
    message: "must be numerical" }
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name,
    presence: true,
    uniqueness: { message: "Manufacturer name has already been used" }

  validates :country,
    presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    @manufacturers = Manufacturer.all
  end
  def new
    @car = Car.new
    @manufacturers = Manufacturer.all.map { |manufacturer| [manufacturer.name, manufacturer.id]}
  end

  def create
    @cars = Car.all
    @car = Car.new(car_params)
    @manufacturers = Manufacturer.all.map { |manufacturer| [manufacturer.name, manufacturer.id]}

    if @car.save
      redirect_to cars_path
      flash[:notice] = "You have successfully entered a new car listing"
    else
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer_id, :color, :year, :mileage, :description)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if @manufacturer.save
     flash[:notice] = "Your manufacturer has been successfully added."
     redirect_to manufacturers_path
    else
     render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/cars/_new_car_form.html.erb
<%= form_for @car do |f| %>
<TABLE>
  <TR>
    <div>
      <TD><%= f.label :manufacturer_id %></TD>
      <TD><%= f.select :manufacturer_id, options_for_select(@manufacturers) %></TD>
    </div>
  </TR>
  <TR>
    <div>
      <TD><%= f.label :color %></TD>
      <TD><%= f.text_field :color %></TD>
    </div>
  </TR>
  <TR>
    <div>
      <TD><%= f.label :year %></TD>
      <TD><%= f.select :year, options_for_select(1920..(Time.now.year.to_i + 1)) %><TD>
    </div>
  </TR>
  <TR>
    <div>
      <TD><%= f.label :mileage %></TD>
      <TD><%= f.text_field :mileage %></TD>
    </div>
  </TR>
  <TR>
    <div>
      <TD><%= f.label :description %></TD>
      <TD><%= f.text_area :description %></TD>
    </div>
  </TR>
  <TR>
    <TD><%= f.submit "Submit Car" %></TD>
  </TR>
  <% end %>
</TABLE>

app/views/cars/index.html.erb
<h2> All Cars </h2>

<%= link_to "Add New Car", new_car_path %>

<TABLE>
  <TR>
    <TD><strong>Manufacturer | </TD>
    <TD><strong>Color</TD>
    <TD><strong>Year</TD>
    <TD><strong>Mileage</TD>
    <TD><strong>Description</TD>
  </TR>
  <% @cars.each do |car| %>
  <TR>
    <TD><%= car.manufacturer.name %></TD>
    <TD><%= car.color %></TD>
    <TD><%= car.year %></TD>
    <TD><%= car.mileage %></TD>
    <TD><%= car.description %></TD>
  </TR>
  <% end %>
</TABLE>

<p><%= link_to "Back", root_path %></p>

app/views/cars/new.html.erb
<% if @car.errors.any? %>
  <%  @car.errors.full_messages.each do |msg| %>
    <li>  <%= msg %>  </li>
    <% end %>
<% end %>

<h2>Fill out the form below to add a car</h2>

<%= render "new_car_form" %>
<%= link_to "Back", cars_path %>

app/views/homes/index.html.erb
<P> Please use the navigation bar on the top of the
  page
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CarListings</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <br>
    <%= link_to 'Home', root_path %> |
    <%= link_to 'View Manufacturers', manufacturers_path %> |
    <%= link_to 'View Cars', cars_path %>
  </br>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/manufacturers/_new_manufacturer_form.html.erb
<%= form_for @manufacturer do |f| %>

<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :country %>
  <%= f.text_field :country %>
</div>

<p>
  <%= f.submit "Submit Manufacturer" %>
</p>

<% end %>

app/views/manufacturers/index.html.erb
<h2> All Manufacturers </h2>

<p><%= link_to 'Add New Manufacturer', new_manufacturer_path(@manufacturer) %></p>

<TABLE>
  <TR>
    <TD><strong>Manufacturer | </TD>
    <TD><strong>Country</TD>
  </TR>
  <% @manufacturers.each do |manufacturer| %>
    <TR>
      <TD><%= manufacturer.name %></TD>
      <TD><%= manufacturer.country %></TD>
    </TR>
  <% end %>
</TABLE>

<p><%= link_to "Back", root_path %></p>

app/views/manufacturers/new.html.erb
<% if @manufacturer.errors.any? %>
  <%  @manufacturer.errors.full_messages.each do |msg| %>
    <li>  <%= msg %>  </li>
  <% end %>
<% end %>

<h2>Fill out the form below to add a manufacturer</h2>

<%= render "new_manufacturer_form" %>
<%= link_to "Back", manufacturers_path %>